
from enum import Enum


class AccessRequestCodes(str, Enum):
  ACCESS_REQUEST_NEW = "ACCESS_REQUEST_NEW"
  ACCESS_REQUEST_MODIFICATION = "ACCESS_REQUEST_MODIFICATION"
  ACCESS_REQUEST_DELETE = "ACCESS_REQUEST_DELETE"
  ACCESS_REQUEST_VALIDATION_UPDATE = "ACCESS_REQUEST_VALIDATION_UPDATE"
