from enum import Enum


class PermissionRequestCodes(str, Enum):
    PERMISSION_REQUEST_NEW = "PERMISSION_REQUEST_NEW"
    PERMISSION_REQUEST_MODIFICATION = "PERMISSION_REQUEST_MODIFICATION"
    PERMISSION_REQUEST_DELETE = "PERMISSION_REQUEST_DELETE"
    PERMISSION_REQUEST_VALIDATION_UPDATE = "PERMISSION_REQUEST_VALIDATION_UPDATE"
