name: Tests

on:
  push:
    paths:
      - "backend/**"
      - "pyproject.toml"
    branches:
      - main
      - develop
  pull_request:
    paths:
      - "backend/**"
      - "pyproject.toml"
    branches:
      - main
      - develop
  workflow_dispatch:

# Annule les exécutions précédentes du même workflow sur la même branche
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    name: Pytest
    uses: PnX-SI/GeoNature/.github/workflows/gn-module-pytest.yml@develop
    with:
      geonature_ref: develop
